site_name: RiskGPT
site_url: https://thwolter.github.io/riskgpt/
theme:
  name: material
nav:
  - Home: index.md
  - LangServe Playground: langserve.md
  - Chains:
      - Get Categories: get_categories.md
      - Check Definition: check_definition.md
      - Get Drivers: get_drivers.md
      - Get Assessment: get_assessment.md
      - Get Mitigations: get_mitigations.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
