# RiskGPT Example Configuration

# Business Context
business_context:
  project_id: "Infrastructure-Risk-Register-001"
  project_description: "Updating the Gas Transport and Storage Infrastructure Assets Risk Register "
  domain_knowledge: "The Risk Register is used to track and manage risks associated with the infrastructure assets (UGS, Transport) of the organization."
  business_area: "Gas Transport and Storage Infrastructure"
  industry_sector: "Energy"

# Existing Risks
existing_risks:
  - title: "Data Security Breach"
    description: "Risk of unauthorized access to sensitive data during migration"
    category: "Security"
  - title: "Service Disruption"
    description: "Risk of service disruption during the migration process"
    category: "Operational"

# Challenge Questions Configuration
challenge_questions:
  audience: "executives"
  focus_areas:
    - "strategic alignment"
    - "technical uncertainty"
    - "operational risks"
  num_questions: 5

# Enrich Context Configuration
enrich_context:
  focus_keywords:
    - "strategic alignment"
    - "technical uncertainty"
    - "operational risks"
  time_horizon_months: 12

# Risk Workflow Configuration
risk_workflow:
  category: "Technical"
  max_risks: 5
