name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync
      - name: Lint
        run: |
          uv run ruff check .
      - name: Type check
        run: uv run mypy src
      - name: Test
        run: uv run pytest --cov=src --cov-fail-under=80 -k "not integration"
      - name: Build docs
        run: uv run mkdocs build --strict
